### ISSUE TITLE
task module rander unnaturally

### ISSUE THREAD

**Issue by DreamMaoMao** [imsi32/yatline.yazi#13]
![image](https://github.com/imsi32/yatline.yazi/assets/30348075/9068f6ae-9065-45a5-abf2-65db1bf17747)

This is missing render after running a task.

**Comment by imsi32** [comment]
I find a way to fix by adding :style(style_c) to [here](https://github.com/sxyazi/yazi/blob/9d0ef9a5dc84fb567df0154140f961d57a4bf6c6/yazi-plugin/preset/components/progress.lua#L24). However, I will check a way that I can add a gauge into line as a component.

**Comment by imsi32** [comment]
Fixed with 24ac767424ae18bf28b1d7ac9a73dbb42cc0b523.
