### ISSUE TITLE
not working with latest yazi update

### ISSUE THREAD

**Issue by soymadip** [imsi32/yatline.yazi#37]
From yesterday, it's not working

**Comment by imsi32** [comment]
I tested on Yazi 0.4.2 and it was working. Which git commit Yazi is on?

Was Yazi able to load with default lines or was it crashed? If it is crashed, can you give error message?

Can you test with only this component in your config:
``` lua
{type = "string", custom = false, name = "hovered_name"},
```

**Comment by soymadip** [comment]
looks like there was some problem with my installlation
reinstalling solved the problem
wierd though it suddlenly stopped..

**Comment by soymadip** [comment]
> I tested on Yazi 0.4.2 and it was working. Which git commit Yazi is on?
> 
> Was Yazi able to load with default lines or was it crashed? If it is crashed, can you give error message?
> 
> Can you test with only this component in your config:
> 
> ```lua
> {type = "string", custom = false, name = "hovered_name"},
> ```

hey by the way, instead of cloning with git as mentioned in wiki, wont it be better to use `ya pack -a` to install?
