### ISSUE TITLE
Theme config behavior

### ISSUE THREAD

**Issue by wekauwau** [imsi32/yatline.yazi#38]
My yatline setup in yazi/init.lua:
```lua
section_separator = { open = "", close = "" },
part_separator = { open = "┃", close = "┃" },
inverse_separator = { open = "", close = "" },
```
But it's replaced by theme config (which doesn't contain separator config above) and back to default. So, I had to place above config in my theme config instead.

I think it's better to make theme config behavior akin to yatline setup behavior (if not configured in yatline setup then use from default yatline), e.g., if not configured in theme then use from yatline setup.

**Comment by imsi32** [comment]
It is doable but it needs a lot of if-statements and people may not know structure of themes so they can accidentally break their themes. Instead of that I think modifying theme in user-space will be more understandable. For example, like this:

``` lua
local catppuccin_theme = require("yatline-catppuccin"):setup("mocha") -- or "latte" | "frappe" | "macchiato"

catppuccin_theme.section_separator = { open = "", close = "" }
catppuccin_theme.part_separator = { open = "┃", close = "┃" }
catppuccin_theme.inverse_separator = { open = "", close = "" }
```

**Comment by wekauwau** [comment]
Thanks! Didn't think of that before
